### ISSUE TITLE
NPS ROR

### ISSUE THREAD

**Issue by juddpatterson** [nationalparkservice/EMLeditor#1]
Have you seen a standard spot to put the NPS ROR in EML? Perhaps there isn't a high-level location that is appropriate, but it would be used at the level of each individual contributor/creator instead. Since there is a single ROR for all of NPS perhaps this package could help with inserting that into the right spot(s).

I don't think this is a high priority, but clearly of some relevance as we saw it when we registered a DOI through DataCite. There is a DataStore connection to unravel as well (since it stores an affiliation but not a ROR at this point).

**Comment by RobLBaker** [comment]
I have not seen a standard spot for RORs. My best guesses as to where they might go would be either with the Publisher (there is a userid field for publishers) or with under project there is a separate space for creator where a userid could go. I would lean towards the first option.

**Comment by RobLBaker** [comment]
Upon further digging, it appears that NCEAS lists organizational RORs as part of the publisher subset of tags. I added a function that will add the publisher info including ROR whenever a set-class function is called (a function that actually makes changes to the EML rather than just viewing portions of it). Optionally, users can add the flag NPS=FALSE to avoid using NPS as a publisher.
