### ISSUE TITLE
Sarah comments

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/EMLeditor#13]
- set.NPSpublisher (and other "set" functions)
	- Consider adding an "replace_existing = c("ask", "yes", "no")" parameter to better support both interactive and non-interactive use
- get.unitPolygon
	- Is this redundant with QCkit::qc_getParkPolygonIRMA?
- get.beginDate/endDate
	- Consider accepting date format as argument (w/sensible default)
- get.citation
	- Can we get publisher from the metadata instead of hard-coding?
- get/set.parkUnits
	- Should we always use this fxn instead of setting more precise bounding coords?
- When are you supposed to use set.DOI vs new.DOI?
- How do the DOI prefixes work?
- write.readme
	- default outfile to "" so that users have option to just dump to console

**Comment by RobLBaker** [comment]
1. Great idea - working on it.
2. Yes, kind of. I pulled it from there and did some updates. I'm anticipating that QCkit becomes a community-drivien/developed package and while I can use the version there, I'm worried it might change and break what's going on here. I'd be happy to hear that's an unsubstantiated concern.
3. Discussed leaving return object as a date rather than a string - will look into this
4. Yes! when this was written, set_publisher didn't exist. Now that publisher info is in the metadata it should be easy to pull from that.
5. I think so; more precise bounding coordinates for specific data collection sites can be specified using EMLassemblyline.
6. Great question. I'll get rid of one of these to reduce redundancy.
7. Briefly, they are pretty static and it should be OK to hardcode them in.
8. Done (but needs some testing).

**Comment by RobLBaker** [comment]
1. done.
2. See above.
3. Stayed string. I don't see a strong need for R-object but will revisit if this comes up again.
4. done
5. see above
6. done
7. see above
8. done
